# Generated by Django 6.0.3 on 2026-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('instructor', 'Instructor'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
