# Generated by Django 6.0.3 on 2026-03-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('oculto', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pagado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('imagen_banner', models.URLField(blank=True)),
                ('imagen_card', models.URLField(blank=True)),
                ('buy_url', models.URLField(blank=True)),
                ('buy_text', models.CharField(default='Comprar ahora', max_length=60)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('destacado', models.BooleanField(default=False)),
                ('mas_vendido', models.BooleanField(default=False)),
                ('oculto', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='catalog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('descripcion', 'Descripción'), ('temario', 'Temario'), ('testimonio', 'Testimonio'), ('imagen', 'Imagen')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('estrellas', models.PositiveSmallIntegerField(default=5)),
                ('contenido', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='catalog.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='catalog.curso')),
            ],
        ),
    ]
