# Generated by Django 6.0.3 on 2026-03-12 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='catalog.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['slug'], name='catalog_cur_slug_1fdbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['-creado'], name='catalog_cur_creado_be9d07_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['usuario', 'curso'], name='catalog_fav_usuario_18707e_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='uniq_favorito_usuario_curso'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['usuario', 'curso'], name='catalog_ins_usuario_b7c91d_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['-fecha'], name='catalog_ins_fecha_2d7123_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='uniq_usuario_curso'),
        ),
    ]
