# Generated by Django 6.0.3 on 2026-03-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('descripcion', 'Descripción'), ('temario', 'Temario'), ('testimonio', 'Testimonio'), ('imagen', 'Imagen'), ('seccion', 'Título de Sección')], max_length=20),
        ),
    ]
