# Generated by Django 6.0.3 on 2026-03-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bloquecontenido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='page_css',
            field=models.TextField(blank=True, default='', verbose_name='CSS de página (GrapesJS)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='page_gjs_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos GrapesJS (JSON)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='page_html',
            field=models.TextField(blank=True, default='', verbose_name='HTML de página (GrapesJS)'),
        ),
    ]
